### ISSUE TITLE
我跟你同样的型号，更新opencore以后CPU显示正常了

### ISSUE THREAD

**Issue by zhao-xinlu** [Lifebrowser/acer-S50-51-EFI#1]
跟你一样的型号，我的是10代的i5。我用OCAuxiliaryTools把你的OC文件更新到0.9.9以后CPU显示正常了，但是WiFi无法驱动（虽然蓝牙是正常的）。

**Comment by zhao-xinlu** [comment]
更新了alpha版本的通用Intel驱动以后WiFi也正常了。现在CPU会被显示为i7，但是可以正常工作，不会一直显示100%。睡眠也正常，鼠标键盘等等其它都正常了。你可以试一试更新，如果需要的话我把我更改过的OC文件给你

**Comment by Lifebrowser** [comment]
谢谢，我把CPUFriend禁用之后是正常的，但个人有点强迫症，想性能释放跟Windows保持一致，目前来看应该不是引导驱动的问题，而是苹果系统压根就没打算兼容第三方硬件的问题😂
